pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r tutorials/build/html .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
